// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFC4VC88noTCRiUP7ZpOX1a6_QAJYfQDM',
    appId: '1:949237855418:web:0ffd60fff20fbf95fa3e83',
    messagingSenderId: '949237855418',
    projectId: 'og-vibes-1f15c',
    authDomain: 'og-vibes-1f15c.firebaseapp.com',
    storageBucket: 'og-vibes-1f15c.appspot.com',
    databaseURL: 'https://og-vibes-1f15c.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcbLLOdJEfNgslQn8TuW1vFe3sYNpgMUI',
    appId: '1:949237855418:android:a9ea44a58349956bfa3e83',
    messagingSenderId: '949237855418',
    projectId: 'og-vibes-1f15c',
    storageBucket: 'og-vibes-1f15c.appspot.com',
    databaseURL: 'https://og-vibes-1f15c.firebaseio.com',
  );
}
